import javax.swing.JOptionPane;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sarthak
 */
public class changepassword extends javax.swing.JFrame {

    /**
     * Creates new form changepassword
     */
    public changepassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2000, 1080));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(2550, 1080));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel1.setText("Enter User ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 130, 170, 33);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(700, 130, 291, 30);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel2.setText("Enter Old Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 220, 250, 40);

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(700, 220, 291, 40);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel3.setText("Enter New Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(399, 300, 240, 33);

        jPasswordField2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(700, 300, 291, 40);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel4.setText("Repeat Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(440, 370, 190, 30);

        jPasswordField3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        getContentPane().add(jPasswordField3);
        jPasswordField3.setBounds(700, 370, 291, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesKYAXSUAL.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(800, 530, 176, 69);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 10, 330, 80);

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 102));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 530, 250, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/8247411-password-hacked-key-in-laptop-on-white-isolated-background-3d.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setMinimumSize(new java.awt.Dimension(2000, 1080));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1610, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String s=jTextField1.getText();
     int d=s.length();
       String z=new String(jPasswordField1.getPassword());
       String query="Select uid,pwd from login where uid like'"+s+"' ;";
          String add="";
String nt="";
         try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
nt=rs.getString(1);
add=rs.getString(2);
                    }}
          catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

if(d>0){
         if(z.equals(add)&&s.equals(nt))
        {String l=new String(jPasswordField2.getPassword());
        String q=new String(jPasswordField3.getPassword());
        if(l.equals(q))
        { String querry="Update login set pwd='"+q+"'where uid like'"+s+"'";
                  try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
          
                      int effect=stmt.executeUpdate(querry);
JOptionPane.showMessageDialog(null,"password successfully changed");
}
                   catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }}
        }}
else{
JOptionPane.showMessageDialog(null,"Failed");
}
jTextField1.setText(null);
            jPasswordField1.setText(null);
jPasswordField2.setText(null);
jPasswordField3.setText(null);

    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new selection().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changepassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
