import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * insertcompany.java
 *
 * Created on Dec 28, 2014, 5:05:00 PM
 */

/**
 *
 * @author Sarthak Samrat
 */
public class insertcompany extends javax.swing.JFrame {

    /** Creates new form insertcompany */
    public insertcompany() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2550, 1080));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(2550, 1080));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 320, 80);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("COMPANY NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 140, 320, 40);

        jTextField1.setToolTipText("ONLY 30 CHARACTERS ALLOWED");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(730, 150, 300, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("COMPANY COUNTRY");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 240, 380, 60);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("COMPANY EMAIL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 340, 330, 42);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(730, 340, 300, 30);

        jComboBox1.setModel(new DefaultComboBoxModel());
        jComboBox1.setToolTipText("click add new on adding new country");
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
        });
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(730, 250, 230, 30);

        jButton1.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        jButton1.setText("Add New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(960, 250, 150, 30);

        jTextField2.setText("Add new Country");
        jTextField2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTextField2ComponentHidden(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(730, 220, 230, 30);

        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("add new country");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(880, 280, 100, 14);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("Contact Number ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(410, 410, 290, 50);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(730, 410, 260, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("Company Address");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 480, 310, 80);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(730, 480, 270, 90);

        jButton2.setFont(new java.awt.Font("Poor Richard", 1, 48)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 153));
        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1060, 620, 250, 50);

        jButton3.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(60, 620, 230, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apple-mac-hd-wallpaper-11.jpg"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1620, 1150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeVisible
        // TODO add your handling code here:
                 DefaultComboBoxModel cm=(DefaultComboBoxModel)jComboBox1.getModel();
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            String query="select countryname from country"+";";
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
               String add=rs.getString(1);

               if(cm.getIndexOf(add)== -1){
                   cm.addElement(add);
               }
                jComboBox1.setModel(cm);
          }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeVisible

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
  String c=jTextField2.getText().toLowerCase();

          try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
          Statement stmt= con.createStatement();


             String q= "Insert into country values ('"+c+"')";
              
             int effect=stmt.executeUpdate(q);
JOptionPane.showMessageDialog(null,"successful");

        }  catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        } 
      


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jLabel1MouseMoved

    private void jTextField2ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTextField2ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ComponentHidden

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        jTextField2.setVisible(false);
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed
        // TODO add your handling code here:
        jTextField2.setVisible(false);
    }//GEN-LAST:event_jComboBox1MousePressed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        jTextField2.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new company().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int add=0;
       int qs=0;
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            String query="select companyid from company"+";";
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
                add=rs.getInt(1);
                qs= add+1;



          }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }


        DefaultComboBoxModel cn=(DefaultComboBoxModel)jComboBox1.getModel();

        try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
     Statement   stmt= con.createStatement();
String name= jTextField1.getText();
String cc=(String)jComboBox1.getSelectedItem();
String email=jTextField3.getText();
String contact=jTextField4.getText();
String address=jTextArea1.getText();

String q= "Insert into company values ('"+qs+"','"+name+"','"+cc+"','"+email+"','"+contact+"','"+address+"');";
int effect=stmt.executeUpdate(q);
JOptionPane.showMessageDialog(null,"successful");
        }  catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
jTextField1.setText(null);
jTextField4.setText(null);
jTextField3.setText(null);
jTextArea1.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insertcompany().setVisible(true);
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
