import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * iNSTALL.java
 *
 * Created on Jan 2, 2015, 3:57:18 PM
 */

/**
 *
 * @author Sarthak Samrat
 */
public class iNSTALL extends javax.swing.JFrame {

    /** Creates new form iNSTALL */
     Statement stmt=null;
        ResultSet rs=null;

    public iNSTALL() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Build tables");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 140, 330, 55);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Build database");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 80, 330, 48);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Step 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 80, 91, 42);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Step 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 140, 99, 42);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel3.setText("Please follow the simple two step procedure to start using your software");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(21, 22, 616, 25);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 102));
        jButton3.setText("Continue");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(450, 220, 150, 37);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ordi-Matrix.gif"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(450, 60, 190, 150);

        jLabel6.setText("NOTE:-- Please ensure that my sql 5.1 is installed on your computer");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 190, 400, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/installation-icon.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 650, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabel5.setVisible(true);
 try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
             stmt= con.createStatement();
            String SQL="create table country(countryname varchar(30) primary key);";
             int e= stmt.executeUpdate(SQL);
        }
 catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
 try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
             stmt= con.createStatement();
            String SQL="insert into country values('India');";
             int e= stmt.executeUpdate(SQL);
        }
 catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
  try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
             stmt= con.createStatement();
            String SQL="insert into country values('Australia');";
             int e= stmt.executeUpdate(SQL);
        }
 catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
   try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
             stmt= con.createStatement();
            String SQL="insert into country values('Nepal');";
             int e= stmt.executeUpdate(SQL);
        }
 catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
             stmt= con.createStatement();
            String SQL="insert into country values('Japan');";
             int e= stmt.executeUpdate(SQL);
        }
 catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
             stmt= con.createStatement();
            String SQL="create table company(companyid integer primary key,companyname varchar(30) unique,companycountry varchar(30),companyemail varchar(50),companycontact varchar(16),address varchar(60));";
             int e= stmt.executeUpdate(SQL);
        }
 catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
 try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
             stmt= con.createStatement();
            String SQL="create table medicines(productid integer primary key,productname varchar(30),companyname varchar(30),productcategory varchar(20) ,narcotic varchar(10),quantity integer,priceperunit integer);";
             int e= stmt.executeUpdate(SQL);
        }
 catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
 try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
             stmt= con.createStatement();
            String SQL="create table login(uid varchar(30) primary key,pwd varchar(30),usertype varchar(30));";
             int e= stmt.executeUpdate(SQL);
      }
 catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
 try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
             stmt= con.createStatement();
            String SQL="insert into login values('admin','admin','Administrator');";
             int e= stmt.executeUpdate(SQL);
      }
 catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
 try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
             stmt= con.createStatement();
            String SQL="create table doctor(doctorname varchar(30),phonenumber varchar(30) primary key,organisation varchar(30),address varchar(30));";
             int e= stmt.executeUpdate(SQL);
       }
 catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
          
           try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
             stmt= con.createStatement();
            String SQL="create table userlogin(uid varchar(30) primary key,pwd varchar(30),usertype varchar(30));";
             int e= stmt.executeUpdate(SQL);
    
           }
 catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
           
            try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
             stmt= con.createStatement();
            String SQL="insert into userlogin values('admin','admin','Administrator');";
             int e= stmt.executeUpdate(SQL);
      }
 catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
                try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
             stmt= con.createStatement();
            String SQL="create table category(category varchar(30));";
             int e= stmt.executeUpdate(SQL);
    
           }
 catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
  try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
             stmt= con.createStatement();
            String SQL="insert into category values('tab');";
             int e= stmt.executeUpdate(SQL);
      }
 catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
   try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
             stmt= con.createStatement();
            String SQL="insert into category values('syrup');";
             int e= stmt.executeUpdate(SQL);
      }
 catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
             try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
             stmt= con.createStatement();
            String SQL="create table tempsale(purchasedate date,customername varchar(30),productname varchar(30),productid integer,quantity varchar(30),amount varchar(30),doctorname varchar(30));";
             int e= stmt.executeUpdate(SQL);
   
           }
 catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
              try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
             stmt= con.createStatement();
            String SQL="create table sale(purchasedate date,customername varchar(30),productname varchar(30),productid integer,quantity varchar(30),amount varchar(30),doctorname varchar(30));";
             int e= stmt.executeUpdate(SQL);
     JOptionPane.showMessageDialog(null,"All tables successfully created"); 
       JOptionPane.showMessageDialog(null,"All set ready to go");   
                jLabel5.setVisible(false);}
 catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
            jLabel5.setVisible(false);
        }
   

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel5.setVisible(true);
        try{

            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306","root","");
            stmt= con.createStatement();
            String SQL="create database med;";
            int e= stmt.executeUpdate(SQL);
            JOptionPane.showMessageDialog(null,"successfully created database");
              jLabel5.setVisible(false);
        } catch (Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());
                jLabel5.setVisible(false);
            }
        
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jLabel5.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iNSTALL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
