import java.awt.print.PrinterException;
import javax.swing.DefaultComboBoxModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * newsales.java
 *
 * Created on Jan 2, 2015, 10:29:41 PM
 */

/**
 *
 * @author Sarthak Samrat
 */
public class newsales extends javax.swing.JFrame {

    /** Creates new form newsales */
    public newsales() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2000, 1080));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(2000, 1080));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 320, 90);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setText("Purchase Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 50, 180, 40);

        jLabel4.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Choose Items");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 110, 180, 33);

        jComboBox1.setModel(new DefaultComboBoxModel());
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(180, 150, 240, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Product Type");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 150, 150, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setText("Product Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 150, 180, 40);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(670, 150, 230, 30);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setText("Search");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(670, 130, 80, 24);

        jComboBox2.setModel(new DefaultComboBoxModel());
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(670, 180, 230, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel8.setText("Enter Quantity");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(990, 150, 160, 40);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(1140, 150, 170, 40);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Price Per Unit");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(570, 230, 160, 20);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(730, 230, 190, 20);

        jLabel11.setFont(new java.awt.Font("Vodafone Lt", 1, 24)); // NOI18N
        jLabel11.setText("TOTAL AMOUNT");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 220, 200, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BILL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36))); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 280, 450, 270);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 51));
        jButton1.setText("Add to Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1060, 580, 210, 50);

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 102));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 570, 160, 60);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Purchase Date", "Customer Name", "Product Name", "Product ID", "Quantity", "Amount", "Doctor Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(580, 260, 700, 260);

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(810, 580, 230, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(230, 220, 160, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(1060, 10, 260, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel13.setText("CUSTOMER NAME");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(830, 10, 230, 30);

        jTextField4.setEditable(false);
        jTextField4.setText("Self");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(1060, 60, 260, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel14.setText("Doctor Name");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(830, 60, 180, 30);

        jButton4.setBackground(new java.awt.Color(102, 255, 204));
        jButton4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 0));
        jButton4.setText("Calculate Bill");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(280, 580, 220, 50);

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton5.setText("PRINT RECEIPT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(530, 580, 250, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5--1260984-Success Text Background - HD1080.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1560, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel cm=(DefaultComboBoxModel)jComboBox1.getModel();

               String tf=(String) jComboBox1.getSelectedItem();
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            String query="select category from category"+";";
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
               String add=rs.getString(1);

               if(cm.getIndexOf(add)== -1){
                   cm.addElement(add);
               }
                jComboBox1.setModel(cm);
          }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:

        DefaultComboBoxModel cp=(DefaultComboBoxModel)jComboBox1.getModel();

               String tf=(String) jComboBox1.getSelectedItem();
        String  text=jTextField1.getText();
         DefaultComboBoxModel cm= (DefaultComboBoxModel) jComboBox2.getModel();
         String query="Select (productname) from medicines where productname like'%"+text+"%' && productcategory like'%"+tf+"%'";
          String add="";

         try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){

                    add=rs.getString(1);

               if(cm.getIndexOf(add)== -1){
                   cm.addElement(add);
               }
                jComboBox2.setModel(cm);
         jComboBox2.setSelectedItem(add);}
         String u=(String) jComboBox2.getSelectedItem();
        
          String querry="select priceperunit from medicines where productname like'"+u+"'";
           ResultSet ts=stmt.executeQuery(querry);
            while(ts.next()){

                  String  op=ts.getString(1);
         jLabel10.setText(op);}
         }
          catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jComboBox2PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeVisible
        // TODO add your handling code here:
       

    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeVisible

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
          DefaultComboBoxModel cp=(DefaultComboBoxModel)jComboBox1.getModel();
 
          String u=(String) jComboBox2.getSelectedItem();
            String query="select priceperunit from medicines where productname like'"+u+"'"; 
         try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){

                   
        
        
          
         
           

                  String  op=rs.getString(1);
         jLabel10.setText(op);
         } String queory="select narcotic from medicines where productname like'"+u+"'";
           ResultSet ys=stmt.executeQuery(queory);
            while(ys.next()){

                  String  op=ys.getString(1);
         if(op.equalsIgnoreCase("YES"))
         {jTextField4.setEditable(true);
         jTextField4.setText(null); }
         else{jTextField4.setEditable(false);
           jTextField4.setText("Self");
         }  }
            
         }
          catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
              
             
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
 
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        DefaultComboBoxModel ct=(DefaultComboBoxModel)jComboBox1.getModel();
 DefaultComboBoxModel ce= (DefaultComboBoxModel) jComboBox2.getModel();
 ce.removeAllElements();
               String tf=(String) jComboBox1.getSelectedItem();
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            String query="select category from category"+";";
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
               String add=rs.getString(1);

               if(ct.getIndexOf(add)== -1){
                   ct.addElement(add);
               }
                jComboBox1.setModel(ct);
          }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        DefaultComboBoxModel cm=(DefaultComboBoxModel)jComboBox2.getModel();
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            String query="select productname from medicines where productcategory like'"+tf+"'";
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
               String add=rs.getString(1);

               if(cm.getIndexOf(add)== -1){
                   cm.removeElement(add);
               }
                jComboBox2.setModel(cm);
          }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }jLabel10.setText(null);
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        // TODO add your handling code here:
          DefaultComboBoxModel cf=(DefaultComboBoxModel)jComboBox2.getModel();
        int n=jComboBox2.getItemCount();
        if(n>0)
        {jComboBox2.removeAllItems();
               jComboBox2.setModel(cf);}
        DefaultComboBoxModel cp=(DefaultComboBoxModel)jComboBox1.getModel();

               String tf=(String) jComboBox1.getSelectedItem();
        DefaultComboBoxModel cm=(DefaultComboBoxModel)jComboBox2.getModel();



        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            String query="select productname from medicines where productcategory like'"+tf+"'";
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
               String add=rs.getString(1);

               if(cm.getIndexOf(add)== -1){
                   cm.addElement(add);
               }
                jComboBox2.setModel(cm);
          } String u=(String) jComboBox2.getSelectedItem();
        
          String querry="select priceperunit from medicines where productname like'"+u+"'";
           ResultSet ts=stmt.executeQuery(querry);
            while(ts.next()){

                  String  op=ts.getString(1);
         jLabel10.setText(op);}
            String queory="select narcotic from medicines where productname like'"+u+"'";
           ResultSet ys=stmt.executeQuery(queory);
            while(ys.next()){

                  String  op=ys.getString(1);
         if(op.equalsIgnoreCase("YES"))
         {jTextField4.setEditable(true);
         jTextField4.setText(null);
         }
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
 String a=(String) jComboBox1.getSelectedItem();
 String b=       (String) jComboBox2.getSelectedItem();
  String c=      jTextField2.getText();
  String w=jTextField4.getText();
   String p=jTextField3.getText();
   String o=jLabel12.getText();
  SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
     String d = sdf.format(jDateChooser1.getDate());
     String add=null;
String Sql="Select productid from medicines where productname like '"+b+"'&& productcategory like '"+a+"';";
DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
 try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
                       ResultSet rs=stmt.executeQuery(Sql);
            while(rs.next()){
                add=rs.getString(1);
            }
  } catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
 try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
           String i="set autocommit= 0 ;";
        int effect=stmt.executeUpdate(i);   
 
  } catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
 try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
       String q= "Insert into tempsale values ('"+d+"','"+p+"','"+b+"','"+add+"','"+c+"','"+o+"','"+w+"')";
        int effect=stmt.executeUpdate(q);   
 
  } catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
   int rows = model.getRowCount();
      
     
       
        if(rows>0)
          for(int i=0; i<rows;i++)
          {model.removeRow(0);
          }
        String query="Select * from tempsale ;";
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
                String pid= rs.getString("purchasedate");
                String pname= rs.getString("customername");
                String cname= rs.getString("productname");
                String pcategory= rs.getString("productid");
                 String ct=rs.getString("quantity");
                String qty= rs.getString("amount");
                String price= rs.getString("doctorname");
                model.addRow(new Object[]{pid,pname,cname,pcategory,ct,qty,price});

            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new selection().setVisible(true);
        this.dispose();

       
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
       String q= "truncate tempsale ;";
        int effect=stmt.executeUpdate(q);   
 
  } catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        } 
       DefaultTableModel model=(DefaultTableModel) jTable1.getModel();  
        int rows = model.getRowCount();
       
      
        if(rows>0)
          for(int i=0; i<rows;i++)
          {model.removeRow(0);
          }
        String query="Select * from tempsale ;";
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
                String pid= rs.getString("purchasedate");
                String pname= rs.getString("customername");
                String cname= rs.getString("productname");
                String pcategory= rs.getString("productid");
                 String ct=rs.getString("quantity");
                String qty= rs.getString("amount");
                String price= rs.getString("doctorname");
                model.addRow(new Object[]{pid,pname,cname,pcategory,ct,qty,price});

            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
              String q=jTextField2.getText();
       int k= q.length();
        if(k>0){
        int n=Integer.parseInt(jLabel10.getText());
        int qty=Integer.parseInt(jTextField2.getText());
        int amt=n*qty;
        jLabel12.setText(""+amt);}
        else{jLabel12.setText(null);}
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
             String q=jTextField2.getText();
       int k= q.length();
        if(k>0){
        int n=Integer.parseInt(jLabel10.getText());
        int qty=Integer.parseInt(jTextField2.getText());
        int amt=n*qty;
        jLabel12.setText(""+amt);}
        else{jLabel12.setText(null);}
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
           String doc=jTextField4.getText();
           int o=doc.length();
           if(o>0){
        jTextArea1.setText("");
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
     String d = sdf.format(jDateChooser1.getDate());
     jTextArea1.append("Date of sale:-"+d+"\n");
    String t= jTextField3.getText();
     jTextArea1.append("Customer Name-"+t+"\n");

     jTextArea1.append("Doctor-"+doc+"\n");
     jTextArea1.append("Details of purchase"+"\n");
     jTextArea1.append("--------------------------------------------------------------------------------------------"+"\n");
          jTextArea1.append("productname"+"\t"+"productid"+"\t"+"quantity"+"\t"+"amount"+"\n");
          jTextArea1.append("--------------------------------------------------------------------------------------------"+"\n");
      String query="Select productname,productid,quantity,amount from tempsale "+";";
      int amt=0;
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
                String pid= rs.getString("productname");
                String pname= rs.getString("productid");
                String cname= rs.getString("quantity");
                String pcategory= rs.getString("amount");
              int r=Integer.parseInt(pcategory);
              amt=amt+r;
                jTextArea1.append(pid+"\t"+pname+"\t"+cname+"\t"+pcategory+"\t"+"\n");}}
              catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        jTextArea1.append("\n"+"total amount= "+amt);
             String querry="INSERT INTO sale select * from tempsale ;";

        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
           
             
        int effect=stmt.executeUpdate(querry);   }
         catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
         try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
       String q= "truncate tempsale ;";
        int effect=stmt.executeUpdate(q);   
 
  } catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        } }
           else{
               JOptionPane.showMessageDialog(this,"Please enter doctor name");
           }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         boolean complete;
        try {
            complete = jTextArea1.print();
        } catch (PrinterException ex) {
            Logger.getLogger(newsales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newsales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
