
import javax.swing.DefaultComboBoxModel;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * updatecompany.java
 *
 * Created on Dec 29, 2014, 7:45:13 PM
 */

/**
 *
 * @author Sarthak Samrat
 */
public class updatecompany extends javax.swing.JFrame {

    /** Creates new form updatecompany */
    public updatecompany() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UpdateCompany");
        setMinimumSize(new java.awt.Dimension(2550, 1080));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(2550, 1080));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 330, 80);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Company Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 90, 250, 40);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(570, 100, 460, 30);

        jComboBox1.setModel(new DefaultComboBoxModel());
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(570, 140, 290, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 51));
        jLabel4.setText("SEARCH");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(570, 70, 80, 22);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Update e-mail");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 200, 240, 40);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(570, 210, 500, 30);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1080, 200, 220, 50);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Update Contact Number");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 250, 370, 60);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(570, 270, 500, 30);

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 0));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1080, 260, 220, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CompanyId", "Country", "email", "phone", "address"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(370, 320, 800, 240);

        jButton4.setFont(new java.awt.Font("Pristina", 1, 48)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 153));
        jButton4.setText("Go Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(70, 570, 240, 70);

        jButton5.setFont(new java.awt.Font("Vodafone ExB", 1, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(204, 0, 0));
        jButton5.setText("Log Out\n\n");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1060, 570, 280, 80);

        jLabel7.setFont(new java.awt.Font("Vodafone Lt", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("CLEAR");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1030, 100, 70, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apple-mac-hd-wallpaper-11.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1630, 1150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
         String  text=jTextField1.getText();
         DefaultComboBoxModel cm= (DefaultComboBoxModel) jComboBox1.getModel();
         String query="Select (companyname) from company where companyname like'%"+text+"%'";
          String add="";

         try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
                
                    add=rs.getString(1);

               if(cm.getIndexOf(add)== -1){
                   cm.addElement(add);
               }
                jComboBox1.setModel(cm);
         jComboBox1.setSelectedItem(add);}}
          catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }


    }//GEN-LAST:event_jTextField1KeyTyped

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
             DefaultComboBoxModel cm=(DefaultComboBoxModel)jComboBox1.getModel();

               String tf=(String) jComboBox1.getSelectedItem();
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            String query="select companyname from company"+";";
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
               String add=rs.getString(1);

               if(cm.getIndexOf(add)== -1){
                   cm.addElement(add);
               }
                jComboBox1.setModel(cm);
          }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
          DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        int rows = model.getRowCount();
        if(rows>0)
          for(int i=0; i<rows;i++)
          {model.removeRow(0);
          }
        String querry="Select * from company where companyname like'%"+tf+"%'";
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(querry);
            while(rs.next()){
                String pid= rs.getString("companyid");
                String pname= rs.getString("companyname");
                String cname= rs.getString("companycountry");
                String pcategory= rs.getString("companyemail");
                String qty= rs.getString("companycontactnumber");
                String price= rs.getString("address");
                model.addRow(new Object[]{pid,pname,cname,pcategory,qty,price});

            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
         DefaultComboBoxModel co= (DefaultComboBoxModel) jComboBox1.getModel();
        String txt=jTextField1.getText();
        int l=txt.length();
        if(l<=0)
        {jComboBox1.removeAllItems();}
        jComboBox1.setModel(co);
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

               DefaultComboBoxModel ct=(DefaultComboBoxModel)jComboBox1.getModel();
               String tf=(String) jComboBox1.getSelectedItem();
                 String query="Update company set companyemail='"+jTextField2.getText()+"'where companyname like'"+tf+"'";
                  try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
          
                      int effect=stmt.executeUpdate(query);
JOptionPane.showMessageDialog(null,"successful");
}
                   catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
                  String  text=jTextField1.getText();
             DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        int rows = model.getRowCount();
        if(rows>0)
          for(int i=0; i<rows;i++)
          {model.removeRow(0);
          }
        String querry="Select * from company where companyname like'%"+tf+"%'";
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(querry);
            while(rs.next()){
                String pid= rs.getString("companyid");
                String pname= rs.getString("companyname");
                String cname= rs.getString("companycountry");
                String pcategory= rs.getString("companyemail");
                String qty= rs.getString("companycontactnumber");
                String price= rs.getString("address");
                model.addRow(new Object[]{pid,pname,cname,pcategory,qty,price});

            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          DefaultComboBoxModel ct=(DefaultComboBoxModel)jComboBox1.getModel();
               String tf=(String) jComboBox1.getSelectedItem();
               int n=Integer.parseInt(jTextField2.getText()) ;
               String query="Update company set companycontactnumber="+n+"where companyname like'"+tf+"'";
                  try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();

                      int effect=stmt.executeUpdate(query);
JOptionPane.showMessageDialog(null,"successful");
}
                   catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
                DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        int rows = model.getRowCount();
        if(rows>0)
          for(int i=0; i<rows;i++)
          {model.removeRow(0);
          }
        String querry="Select * from company where companyname like'%"+tf+"%'";
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(querry);
            while(rs.next()){
                String pid= rs.getString("companyid");
                String pname= rs.getString("companyname");
                String cname= rs.getString("companycountry");
                String pcategory= rs.getString("companyemail");
                String qty= rs.getString("companycontactnumber");
                String price= rs.getString("address");
                model.addRow(new Object[]{pid,pname,cname,pcategory,qty,price});

            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:
         DefaultComboBoxModel cm=(DefaultComboBoxModel)jComboBox1.getModel();

               String tf=(String) jComboBox1.getSelectedItem();
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            String query="select companyname from company"+";";
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
               String add=rs.getString(1);

               if(cm.getIndexOf(add)== -1){
                   cm.addElement(add);
               }
                jComboBox1.setModel(cm);
          }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
          DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        int rows = model.getRowCount();
        if(rows>0)
          for(int i=0; i<rows;i++)
          {model.removeRow(0);
          }
        String querry="Select * from company where companyname like'%"+tf+"%'";
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(querry);
            while(rs.next()){
                String pid= rs.getString("companyid");
                String pname= rs.getString("companyname");
                String cname= rs.getString("companycountry");
                String pcategory= rs.getString("companyemail");
                String qty= rs.getString("companycontactnumber");
                String price= rs.getString("address");
                model.addRow(new Object[]{pid,pname,cname,pcategory,qty,price});

            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jComboBox1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeVisible
        // TODO add your handling code here:

          DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        int rows = model.getRowCount();
        if(rows>0)
          for(int i=0; i<rows;i++)
          {model.removeRow(0);
          }
        String querry="Select * from company ;";
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(querry);
            while(rs.next()){
                String pid= rs.getString("companyid");
                String pname= rs.getString("companyname");
                String cname= rs.getString("companycountry");
                String pcategory= rs.getString("companyemail");
                String qty= rs.getString("companycontactnumber");
                String price= rs.getString("address");
                model.addRow(new Object[]{pid,pname,cname,pcategory,qty,price});

            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeVisible

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
         DefaultComboBoxModel cm=(DefaultComboBoxModel)jComboBox1.getModel();

               String tf=(String) jComboBox1.getSelectedItem();
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            String query="select companyname from company"+";";
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
               String add=rs.getString(1);

               if(cm.getIndexOf(add)== -1){
                   cm.addElement(add);
               }
                jComboBox1.setModel(cm);
          }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
          DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        int rows = model.getRowCount();
        if(rows>0)
          for(int i=0; i<rows;i++)
          {model.removeRow(0);
          }
        String querry="Select * from company where companyname like'%"+tf+"%'";
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/med","root","");
            Statement stmt= con.createStatement();
            ResultSet rs=stmt.executeQuery(querry);
            while(rs.next()){
                String pid= rs.getString("companyid");
                String pname= rs.getString("companyname");
                String cname= rs.getString("companycountry");
                String pcategory= rs.getString("companyemail");
                String qty= rs.getString("companycontactnumber");
                String price= rs.getString("address");
                model.addRow(new Object[]{pid,pname,cname,pcategory,qty,price});

            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new company().setVisible(true);
            this.dispose();
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
            this.dispose();
}//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        jTextField1.setText(null);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatecompany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
